classdef Query < handle
    properties (Constant)
        ZillowWebService = 'http://www.zillow.com/webservice/GetDeepSearchResults.htm?';
        ZWSID = 'X1-ZWz1f8wdb88lxn_1y8f9';
    end
    
    methods (Access = public)
        function info = exec(this, address)
            queryCommand = sprintf('%szws-id=%s%s', this.ZillowWebService, this.ZWSID, this.getAddressQuery(address));
            xmlData = webread(queryCommand);
            info = this.parse(xmlData);
        end               
    end
    
    methods (Static, Access = public)
        function item = parse(xmlData)
            fileName = fullfile(tempdir, 'tempname');
            this.write(xmlData);
            info = zillow.xml2struct(fileName);
            delete(fileName);
            
            % Update the output data
            if (~strcmp(info.SearchResults_colon_searchresults.message.code, '0'))
                error('Cannot query the information of this house: %s %s', ...
                        info.SearchResults_colon_searchresults.request.address.Text, ...
                        info.SearchResults_colon_searchresults.request.citystatezip.Text);
            end
            results = info.SearchResults_colon_searchresults.response.results.result;
            item = struct(...
                'Link', results.links.homedetails.Text, ...
                'Address', results.address.street.Text, ...
                'City', results.address.city.Text, ...
                'ZipCode', results.address.zipcode.Text, ...
                'UseCode', results.useCode.Text, ...
                'TaxAssessment', str2double(results.taxAssessment.Text), ...
                'TaxAssessmentYear', str2double(results.taxAssessmentYear.Text), ...
                'YearBuilt', str2double(results.yearBuilt.Text), ...
                'LotSizeSqFt', str2double(results.lotSizeSqFt.Text), ...
                'FinishedSqFt', str2double(results.finishedSqFt.Text), ...
                'bedrooms', str2double(results.bedrooms.Text), ...
                'TotalRooms', str2double(results.totalRooms.Text), ...
                'LastSoldDate', results.lastSoldDate.Text, ...
                'LasSoldPrice', str2double(results.lastSoldPrice.Text), ...
                'ZEstimate', str2double(results.zestimate.amount.Text));
        end
        
        function write(fileName, xmlData)
            fid = fopen(fileName, 'wt');
            fprintf(fid, '%s\n', xmlData);
            fclose(fid);
        end
        
        function cmd = getAddressQuery(address)
            cmd = sprintf('&address=%d+%s+%s&citystatezip=%s%s+%s', ...
                          address.Number, address.StreetName, address.StreetSuffix, ...
                          address.City, '%2C', address.State);
        end
    end
end

%zws-id=<ZWSID>&address=2114+Bigelow+Ave&citystatezip=Seattle%2C+WA
